# Technology

## Wiki

The lab wiki has all of the information you need to get started in the BABLab, including a checklist of tasks that need to be done upon arrival (onboarding), links to our studies, day-to-day housekeeping duties, examples of forms, flyers, posters that can be used as a starting point when designing your own, programming and stats tips, information about accessing Hoffman2 (the high performance computing cluster), the best places to eat and drink on and around campus, and anything else we can think of. The wiki is a living document and you can contribute to it! When you obtain information that will be useful for others to know (you found the best coffee on campus, a great website or educational resource etc.) put it on the wiki! Ask the lab manager to be added as a member of the wiki so that you can edit it.
 
## Slack

If you haven’t already found this out for yourself, emails are a clunky way of communicating for most lab needs. Moreover, most people will find that they have a backlog of emails awaiting their attention. For this reason, we will use Slack for the primary means of lab communication.

The beauty of Slack is that you only subscribe to the channels that concern you. For messages to one person or a small group, use direct messages. If you have to include out-of-lab recipients, use e-mail. If you have a paper that you want to share, first - save it on the server (CallaghanLab/BAB/PDF_library) using the file format: Firstauthorname_date_studydescription.pdf. Then make a link to the paper online and paste that link into slack using the the same name as the PDF as well as a description of the paper. 
 
Full-time lab members should install Slack on their computers and/or phones and check it regularly (during working hours). Part-time lab members should also check Slack when they are working in the lab as there may be important messages in there for them.
 
Of course, if there is an emergency, and you need to contact Bridget, use her email or phone or drop into her office.

| Slack Channel  | Purpose                                                                                                            |
| -------------- | ------------------------------------------------------------------------------------------------------------------ |
| #mb-methods    | Sharing wisdom on microbiome data collection / analysis or asking and answering the microbiome questions of others |
| #frmri-methods | Sharing wisdom on fMRI data collection / analysis or asking (and answering) the fMRI questions of others           |
| #code-tips     | Sharing wisdom on code writing or asking (and answering) the coding questions of others                            |
| #papers        | Sharing links to lab-relevant papers and discussing them                                                           |
| #lab-meetings  | Notes or communication related to lab meetings                                                                     |
| #random        | Non-work-related chatting – e.g., pics of pets, funny cartoons etc.                                                |
| #stats         | Ask and answer questions about statistical analyses                                                                |

## Server

Any lab related files should be stored on the server under your user folder, not on your personal computer. copies of PDFs of papers we think are interesting to the lab (and link to them on Slack), code for experiments, data from experiments (not fMRI data). The server is organized into directories based on projects and studies within projects. 
 
Connecting to the CallaghanLab server:
 
*Contact the lab manager first to set up your credentials.
 
On a Mac –

- From the dropdown menu under "Go", select “Connect to Server...” (Apple + K)
- Enter the network/server address: `smb://pythia.psych.ucla.edu/Users/CallaghanLab/`
- Click on “Connect”.
- A dialogue box will prompt you for your credentials. Enter your credentials obtained from Psychology IT and click on “OK”.
- If everything was entered correctly from above, the mapped drive will appear under "Shared" in the Mac's Finder.

 
On a PC –

- From the Windows file explorer, right mouse click on "Computer" for Windows 7 or "This PC" on Windows 8/10.
- Select "Map network drive".
- Specify an available "Drive" letter from the dropdown menu.
- Enter the network/server location for the "Folder" field and click on "Finish".
    - Network/server location: `\\pythia.psych.ucla.edu\Users\CallaghanLab\`
- Enter your username and password that was provided by Psychology IT in the "network credentials" popup dialogue box and click on OK.
- If everything was entered correctly from above, the mapped drive will appear under "Network locations" when you click on "Computer/This PC".
- After the drive has been mapped, logged out of Windows to "logout" from the network drive.
- Don't right mouse click on the mapped drive and select "Disconnect". This will only unmap the network drive and you will have to go through the process all over again.

 
To connect off-campus connect to the UCLA/BOL VPN and let it run in the background prior to logging into the mapped drive you had configured on your computer.

How-to download/install the [Cisco VPN client](https://help.bol.ucla.edu/kb_view.do?sysparm_article=kb0010923).


> Every night the server is backed up to the Life Sciences data center in Hershey Hall.  That's always been the case.  To make those nightly backups more safe, there is another copy of the backups stored offsite (i.e. to prevent losing both the server AND the backups in a fire, earthquake, etc.)
> 
> Once we have Shadow Copy enabled, we'll also have more direct access to backups, so we won't need to work with Life Sciences to retrieve backups.  Psych IT will be able to grab a recent copy of your files/folders ourselves.  We'll also have access to incremental backups (i.e. yesterday's copy, two day old copy, three day old copy...up to two weeks back).
> 
> So at that point we'll have 3 forms of backup, and plenty of safety net.
> 
> - Dave (Psych IT)

## Dropbox Paper

The lab has a shared Dropbox Paper account —which is slightly different than regular Dropbox file storage. On the Dropbox Paper, we will place collaborative documents and lab protocols —including study protocols, general lab protocols, onboarding protocols, etc. We will grant you access permission to various folders in the Dropbox Paper account, but we will always link to these protocols elsewhere (from the CallaghanLab server, OSF, or Wiki) —so no need to organize or download these files to your own Dropbox, but you may need to initialize an account with the email we grant access permission.
 
## GitHub

The lab’s GitHub should be used to share code and data with people outside of the lab (i.e., people not on our IRB). Not all data can be shared (because of IRB restrictions) and not all data that can be shared should be shared immediately. Speak with Bridget about when to share data, and what needs to be done to the data (e.g., the level of de-identification required) before we share it. Ask the lab manager to get access to the lab’s GitHub.
 
## Google Calendars

The lab has many Google calendars and you should subscribe to those that make sense for your unique situation.
 

1. BABLab Meetings and Events: Used for lab meetings, out of schedule meetings, birthdays, formal lab events etc.

 

2. Availability: If you are going to be away, you need to place the dates and times on this calendar. This is critical as the lab manager will use this information when scheduling people to run participants for the general lab (longitudinal) study. Bridget will also put her out of office times on this calendar to help people with scheduling.  

 

3. Room 1: used to reserve time in experimental room 1 – we will think of better names for these rooms later.

 

4. Room 2: used to reserve time in experimental room 2 – we will think of better names for these rooms later.

 

5. Computer reservations: used to reserve one of the two MacBook laptops. Laptops should be used for running experiments in lab and at the MRI. If they are available and not in use for an experiment, you may also use the lap tops for entering data and doing other research assistant tasks.

## E-mail

We have several listservs.
 

1. BABLab_core: this will email the BABLab PI (Bridget), postdocs, graduate students, lab managers, and paid research assistants/technicians. - bablab_core@googlegroups.com
2. BABLab_RA: this will email all of the BABLab Ras and lab managers, not the grad students, postdocs, or PI. - bablab_ragooglegroups.com
3. BABLab_extended: this will email all of those people in BABLab_core + all of the undergraduate research assistants and volunteers, students from other labs who attend our meetings, visiting scholars etc. - bablab_extended@googlegroups.com

If you are thinking about joining the lab and would like to be notified about upcoming lab meetings, please request to join the BABLab_extended listserv. 
 
There is also a lab email account which people use to contact the lab to participate in studies (bablab.ucla@gmail.com). This email account will be staffed by the lab manager/s and they will sort the emails in the people’s inboxes within the Gmail account. If you are running a study, it is your responsibility to check your inbox on the lab Gmail every few days and respond to participant inquiries.